# real_accounts.py

# List of real Pakistani Instagram accounts that are publicly accessible,
# but cannot be extracted using automated tools from within Pakistan.
# These restrictions are enforced by Instagram, often due to heightened platform controls
# triggered by India–Pakistan tensions and media conflict.

RESTRICTION_REASON = "Restricted for automated extraction from within Pakistan due to Instagram enforcement likely tied to India–Pakistan media conflict."

REAL_BLOCKED_ACCOUNTS = {
    # 🎭 Actors / Actresses
    "mahirahkhan": RESTRICTION_REASON,
    "haniaheheofficial": RESTRICTION_REASON,
    "fawadkhan81": RESTRICTION_REASON,
    "ali_zafar": RESTRICTION_REASON,
    "sajalaly": RESTRICTION_REASON,
    "iiqraaziz": RESTRICTION_REASON,
    "sanashaikhofficial": RESTRICTION_REASON,
    "bilalabbas_khan": RESTRICTION_REASON,
    "imranabbas.official": RESTRICTION_REASON,
    "mawrellous": RESTRICTION_REASON,
    "ayezakhan.ak": RESTRICTION_REASON,
    "aiman.khan.official": RESTRICTION_REASON,
    "danishtaimoor16": RESTRICTION_REASON,
    "humayunsaeedofficial": RESTRICTION_REASON,
    "ushnashah": RESTRICTION_REASON,
    "yumna.zaidi": RESTRICTION_REASON,
    "ahadrazamir": RESTRICTION_REASON,
    "hira.mani": RESTRICTION_REASON,
    "manshapasha": RESTRICTION_REASON,
    "zarnishkhan": RESTRICTION_REASON,
    "sarahkhanofficial": RESTRICTION_REASON,
    "minalkhan.official": RESTRICTION_REASON,
    "sabaqamarzaman": RESTRICTION_REASON,
    "kinzayhashmi": RESTRICTION_REASON,
    "mehwishhayatofficial": RESTRICTION_REASON,
    "goharfarooqi": RESTRICTION_REASON,
    "omerfarooqofficial": RESTRICTION_REASON,
    "laila.zuberi": RESTRICTION_REASON,

    # 🎤 Singers / Musicians
    "atifaslam": RESTRICTION_REASON,
    "mominamustehsan": RESTRICTION_REASON,
    "abidaparveen.official": RESTRICTION_REASON,
    "officialrfakworld": RESTRICTION_REASON,
    "alihamza": RESTRICTION_REASON,
    "sahirmehmood": RESTRICTION_REASON,
    "abeeralvi": RESTRICTION_REASON,
    "ali_sethi": RESTRICTION_REASON,
    "asimmusic": RESTRICTION_REASON,
    "quratulainbaloch": RESTRICTION_REASON,
    "bilalmashiofficial": RESTRICTION_REASON,
    "bohemiapoet": RESTRICTION_REASON,
    "naziaiqbal": RESTRICTION_REASON,
    "haroonmusicofficial": RESTRICTION_REASON,
    "hadiqakianiofficial": RESTRICTION_REASON,
    "farihazama_official": RESTRICTION_REASON,
    "christhestock": RESTRICTION_REASON,

    # 🏏 Cricketers / Athletes
    "safridiofficial": RESTRICTION_REASON,
    "babarazam": RESTRICTION_REASON,
    "mrizwanpak": RESTRICTION_REASON,
    "wasimakramlive": RESTRICTION_REASON,
    "ishaheenafridi10": RESTRICTION_REASON,
    "shoaibmalik": RESTRICTION_REASON,
    "shadab0800": RESTRICTION_REASON,
    "imamulhaq12": RESTRICTION_REASON,
    "naseemshahofficial": RESTRICTION_REASON,
    "harisrauf": RESTRICTION_REASON,
    "muhammadhafeez": RESTRICTION_REASON,
    "mohammadamir": RESTRICTION_REASON,
    "mohammadyousufofficial": RESTRICTION_REASON,
    "azeemrauf": RESTRICTION_REASON,
    "arshadhafeez": RESTRICTION_REASON,

    # 📢 Influencers / YouTubers / TikTokers / Vloggers
    "irfan.junejo": RESTRICTION_REASON,
    "shahveerjay": RESTRICTION_REASON,
    "dananeerr": RESTRICTION_REASON,
    "romaisa.khan": RESTRICTION_REASON,
    "nashitijaz": RESTRICTION_REASON,
    "junaid.akram": RESTRICTION_REASON,
    "rameeesh": RESTRICTION_REASON,
    "ukhtiarofficial": RESTRICTION_REASON,
    "syeda.umerah": RESTRICTION_REASON,
    "areebazamanzada": RESTRICTION_REASON,
    "waliya.najib": RESTRICTION_REASON,
    "rimshaakhan": RESTRICTION_REASON,
    "junaidali_97": RESTRICTION_REASON,
    "iamzarnab": RESTRICTION_REASON,
    "nadiralinaqvi": RESTRICTION_REASON,
    "dollyofficial1": RESTRICTION_REASON,
    "duckybhai": RESTRICTION_REASON,
    "nadiraliz": RESTRICTION_REASON,
    "bhatti_sajid": RESTRICTION_REASON,
    "maazsafder": RESTRICTION_REASON,
    "laraibrahim": RESTRICTION_REASON,
    "sistrology": RESTRICTION_REASON,
    "saraalikhan95": RESTRICTION_REASON,
    "kiran_ashfaque": RESTRICTION_REASON,
    "syed_basit_ali": RESTRICTION_REASON,
    "mashal_khan": RESTRICTION_REASON,
    "shahzadshow": RESTRICTION_REASON,
    "mashalkhanofficial": RESTRICTION_REASON,
    "areeb.official": RESTRICTION_REASON,
    "rabeeca_khan": RESTRICTION_REASON,
    "mughal_comedy": RESTRICTION_REASON,
    "harrisdev": RESTRICTION_REASON,
    "kanwal.iftikhar": RESTRICTION_REASON,
    "ch.zulqarnain25": RESTRICTION_REASON,
    "alihaiderofficial": RESTRICTION_REASON,
    "hamzabrohi": RESTRICTION_REASON,
    "zarnain_ikram": RESTRICTION_REASON,
    "sumia_official": RESTRICTION_REASON,
    "dastageer.official": RESTRICTION_REASON,
    "yasirshami": RESTRICTION_REASON,
    "asimcreators": RESTRICTION_REASON,
    "its_mahnoor1": RESTRICTION_REASON,
    "zulekhanasiddiquiofficial": RESTRICTION_REASON,
    "wajahatmirza": RESTRICTION_REASON,
    "roohibeauty": RESTRICTION_REASON,
    "nadiascreenshot": RESTRICTION_REASON,

    # 📺 Hosts / Journalists / Public Figures
    "waseembadar": RESTRICTION_REASON,
    "iqrarulhassan": RESTRICTION_REASON,
    "kashifabbasiary": RESTRICTION_REASON,
    "mansoorali_khan": RESTRICTION_REASON,
    "mubasherlucman": RESTRICTION_REASON,
    "sabirshakirary": RESTRICTION_REASON,
    "nadirkhanlive": RESTRICTION_REASON,
    "faisalquraishi": RESTRICTION_REASON,
    "jasmeenmanzoor": RESTRICTION_REASON,
    "ammaranasir": RESTRICTION_REASON,
    "hamidmir": RESTRICTION_REASON,
    "asimnazirofficial": RESTRICTION_REASON,
    "gul_bukhari": RESTRICTION_REASON,
    "omarparacha": RESTRICTION_REASON,
    "rehmanmalik": RESTRICTION_REASON,
    "ganjiswag": RESTRICTION_REASON
}
